name: Node.js Express CI

on:
  push:
    branches: [ Development ]
 
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint
        continue-on-error: true

      - name: Run tests
        run: npm test

      - name: Build (if applicable)
        run: npm run build
        #if: ${{ hashFiles('package.json', 'package-lock.json') != '' && exists('package.json') && contains(join(fromJson(steps.install-deps.outputs.packages)), 'build') }}

        
  # Optionally, add a job to deploy or publish if needed